database:
  autoMigrate: true # Migrate the database schema on startup
  database: QA_CUCM_CDR # Database name
  driver: mssql # Database driver (mysql|mssql|postgres|sqlite)
  host: hostname # Database host
  limit: 100 # Maximum number of records to insert in bulk
  password: pass # Database password
  #path: ./go_cdr.db # Path to the database file (sqlite only)
  port: 1433 # Database port
  username: user # Database username
  SSL: require #Database SSL mode (disable|require|verify-ca|verify-full)
logging:
  compress: false # Compress log files
  level: debug # Logging level (debug|info|warn|error|fatal|panic)
  maxAge: 60 # Maximum age of log files in days
  maxSize: 1000 # Maximum size of log files in megabytes
  name: go-cdr.log # Name of the log files
  path: ./logs # Path to store log files
parser:
  parseInterval: 30 # Interval in minutes to parse files
  directories:
  - input: G:\SFTP_OpenSSH_Root\QA_CUCM_CDR # Path to the CDR files
    output: G:\SFTP_OpenSSH_Root\QA_CUCM_CDR_Processed # Path to move the CDR files after parsing
    type: cucm # Type of CDR files (cucm|cube)
    deleteOriginal: false # Delete original files after parsing
