database:
  autoMigrate: true # Migrate the database schema on startup
  database: cdr # Database name
  driver: mssql # Database driver (mysql|mssql|postgres|sqlite)
  host: 127.0.0.1 # Database host
  limit: 100 # Maximum number of records to insert in bulk
  password: ncxRG3dSgrwNyp8J6hVHtK # Database password
  # path: ./go_cdr.db # Path to the database file (sqlite only)
  port: 1433 # Database port
  username: sa # Database username
  SSL: disable # Database SSL mode (disable|require|verify-ca|verify-full)
logging:
  compress: false # Compress log files
  level: info # Logging level (debug|info|warn|error|fatal|panic)
  maxAge: 30 # Maximum age of log files in days
  maxSize: 100 # Maximum size of log files in megabytes
  name: go-cdr.log # Name of the log files
  path: ./logs # Path to store log files
parser:
  parseInterval: 1 # Interval in minutes to parse files
  directories:
  - input: /Users/ziondials/Projects/Go-CDR/data # Path to the CDR files
    output: /Users/ziondials/Projects/Go-CDR/data/processed # Path to move the CDR files after parsing
    type: cube # Type of CDR files (cucm|cube)
    deleteOriginal: true # Delete original files after parsing
